### ISSUE TITLE
Corriger récupération du contenu des textes chez Factiva

### ISSUE THREAD

**Issue by lisboarocha** [josquindebaz/Tiresias#21]
Factiva a encore une fois changé le format des fichiers, enlevant cette fois-ci les balises qui indiquaient ce que chaque champ était. Dès lors, le contenu des textes n'est plus récupéré, seulement leur titre.

Il faudrait adapter le script au nouveau format.

PS: Github ne me laisse pas téléverser ici un fichier html pour l'exemple.

**Comment by josquindebaz** [comment]
Il faut soit m'envoyer des fichiers, soit me donner un accès à Factiva. Sans cela, pas de mise à jour

**Comment by josquindebaz** [comment]
https://github.com/josquindebaz/Tiresias/pull/31
